dist: xenial

language: python
python:
  - "3.7"

notifications:
  email:
    - powen@renci.org
    - bizon@renci.org
    - kebedey@renci.org

# command to install dependencies
install:
  - wget http://repo.continuum.io/archive/Anaconda3-4.0.0-Linux-x86_64.sh
  - bash Anaconda3-4.0.0-Linux-x86_64.sh
  - conda update
  - conda config --add channels conda-forge
  - conda install --yes --file requirements.txt

env:
  global:
    - PYTHONPATH=$PWD:$PWD/tests

# command to run tests
script:
  - pytest -p no:warnings tests

after_success:
  - coveralls