version: "3"
services:
  neo4j-kp:
    build:
      context: ./
    container_name: neo4j-kp
    image: neo4j:3.5.4
    entrypoint:
      - /bin/sh
      - -c
      - "chown neo4j:neo4j /ssl && /docker-entrypoint.sh neo4j"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_dbms_connectors_default__listen__address=${NEO4J_HOST}
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*  # un-sandbox apoc procedures: http://blog.armbruster-it.de/2017/05/running-neo4j-3-2-apoc-docker/
      - NEO4J_dbms_connector_https_listen__address=${NEO4J_HOST}:${NEO4J_HTTPS_PORT}
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
      - "${NEO4J_HTTPS_PORT}:${NEO4J_HTTPS_PORT}"
    volumes:
      - ../../../neo4j_data:/data
      - ../../../neo4j_logs:/logs
      - ../../../neo4j_ssl:/ssl