version: "3"
services:
  CNKP-Compose:
    build:
      context: ./
    container_name: cnkp_deploy
    image: cnkp
    volumes:
      - /d/dvols/cn/data:/data
      - /d/dvols/cn/logs:/logs
      - /d/dvols/cn/ssl:/ssl
    entrypoint:
      - /bin/sh
      - -c
      - "chown neo4j:neo4j /ssl && /docker-entrypoint.sh neo4j"
#    stdin_open: true
#    tty: true
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_dbms_connectors_default__listen__address=${NEO4J_HOST}
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*  # un-sandbox apoc procedures: http://blog.armbruster-it.de/2017/05/running-neo4j-3-2-apoc-docker/
      - NEO4J_dbms_connector_https_listen__address=${NEO4J_HOST}:${NEO4J_HTTPS_PORT}
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_HEAP_MEMORY}
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_HEAP_MEMORY_INIT}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_CACHE_MEMORY}
      - JAVA_HOME=${JAVA_HOME}
      - NEO4J_dbms_jvm_additional=${NEO4J_dbms_jvm_additional}
      - APOC_URI=${APOC_URI}
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
      - "${NEO4J_HTTPS_PORT}:${NEO4J_HTTPS_PORT}"
