apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f /opt/cn-neo4jkp/~tmp.yml -o kubefiles/cn-neo4jkp-kube-conf.yml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: cn-neo4jkp
    name: cn-neo4j-kp
  spec:
    type: LoadBalancer
    loadBalancerIP: 0.0.0.0 # replace with real IP
    ports:
    - name: '7474'
      port: 7474
      targetPort: 7474
    - name: '7687'
      port: 7687
      targetPort: 7687
    selector:
      io.kompose.service: cn-neo4jkp

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f /opt/cn-neo4jkp/~tmp.yml -o kubefiles/cn-neo4jkp-kube-conf.yml kubefiles/cn-neo4jkp-kube-conf.yml
      kompose.version: 1.7.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: cn-neo4jkp
    name: cn-neo4j-kp
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: cn-neo4jkp
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cn-neo4jkp
      spec:
        containers:
        - command:
          - /bin/sh
          env:
          - name: JAVA_HOME
            value: /usr/lib/jvm/java-11-openjdk/jre
          - name: NEO4J_AUTH
            value: neo4j/neo4jkp
          - name: NEO4J_dbms_connectors_default__listen__address
            value: 0.0.0.0
          - name: NEO4J_dbms_memory_heap_initial__size
            value: 4G
          - name: NEO4J_dbms_memory_heap_max__size
            value: 4G
          - name: NEO4J_dbms_memory_pagecache_size
            value: 4G
          - name: NEO4J_dbms_read__only
            value: 'false'
          - name: NEO4J_dbms_security_procedures_unrestricted
            value: apoc.*
          image: renciorg/neo4jkp
          name: cn-neo4j-kp
          ports:
            - containerPort: 7474
            - containerPort: 7687
          resources: {}
          stdin: true
          tty: true
          imagePullPolicy: Always
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
