apiVersion: v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      service: cn-neo4j-kp-svc
    name: cn-neo4j-kp-dep
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: cn-neo4j-kp-svc
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: cn-neo4j-kp-svc
      spec:
        containers:
        - command:
          - /bin/sh
          - -c
          - "chown neo4j:neo4j /ssl && /docker-entrypoint.sh neo4j"
          env:
          - name: JAVA_HOME
            value: /usr/lib/jvm/java-11-openjdk/jre
          - name: NEO4J_AUTH
            value: neo4j/neo4jkp
          - name: NEO4J_dbms_connectors_default__listen__address
            value: 0.0.0.0
          - name: NEO4J_dbms_memory_heap_initial__size
            value: 4G
          - name: NEO4J_dbms_memory_heap_max__size
            value: 4G
          - name: NEO4J_dbms_memory_pagecache_size
            value: 4G
          - name: NEO4J_dbms_read__only
            value: 'false'
          - name: NEO4J_dbms_security_procedures_unrestricted
            value: apoc.*
          image: renciorg/neo4jkp
          name: cn-neo4j-kp
          ports:
            - containerPort: 7474
            - containerPort: 7687
          resources: {}
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /data
            name: neo4j-data-volume
          - mountPath: /logs
            name: neo4j-logs-volume
          - mountPath: /ssl
            name: neo4j-ssl-volume
        restartPolicy: Always
        volumes:
          - name: neo4j-data-volume
            persistentVolumeClaim:
              claimName: neo4jkp-data-pvc
          - name: neo4j-logs-volume
            persistentVolumeClaim:
              claimName: neo4jkp-logs-pvc
          - name: neo4j-ssl-volume
            persistentVolumeClaim:
              claimName: neo4jkp-ssl-pvc
  status: {}

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: cn-neo4j-kp-svc
    name: cn-neo4j-kp-svc
  spec:
    type: NodePort
    selector:
      service: cn-neo4j-kp-svc
    ports:
    - name: '7474'
      port: 7474
    - name: '7687'
      port: 7687
kind: List
metadata: {}