apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: neo4jkp-data-pv
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    nfs:
      path: C:\Users\kebedey\robokop\neo4j_data
      server: yaphet-x1
    persistentVolumeReclaimPolicy: Retain
    storageClassName: robokop-neo4j-data-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: neo4jkp-data-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: neo4jkp-data-pv
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: neo4jkp-logs-pv
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    nfs:
      path: C:\Users\kebedey\robokop\neo4j_logs
      server: yaphet-x1
    persistentVolumeReclaimPolicy: Retain
    storageClassName: neo4jkp-logs-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: neo4jkp-logs-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: neo4jkp-logs-pv
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: neo4jkp-ssl-pv
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Ki
    nfs:
      path: C:\Users\kebedey\robokop\neo4j_ssl
      server: yaphet-x1
    persistentVolumeReclaimPolicy: Retain
    storageClassName: neo4jkp-ssl-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: neo4jkp-ssl-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Ki
    storageClassName: neo4jkp-ssl-pv
kind: List
