apiVersion: v1
kind: Service
metadata:
  name: neo4j-kp
spec:
  type: NodePort
  selector:
    app: neo4j-kp
  ports:
  - protocol: TCP
    port: 7474
    targetPort: 7474
  - protocol: TCP
    port: 7687
    targetPort: 7687
  - protocol: TCP
    port: 7473
    targetPort: 7473
