apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-kp-deployment
  labels:
    service: neo4j-kp
    app: neo4j-kp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-kp
  template:
    metadata:
      labels:
        app: neo4j-kp
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: neo4j-kp
        image: neo4j:3.5.4
        ports:
          - containerPort: 7474
            name: neo4j_http
          - containerPort: 7687
            name: neo4j_bolt
          - containerPort: 7473
            name: neo4j_https
      restartPolicy: Always
