apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-kp-deployment
  labels:
    service: neo4j-kp
    app: neo4j-kp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-kp
  template:
    metadata:
      labels:
        app: neo4j-kp
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: neo4j-kp
        image: renciorg/neo4jkp
        ports:
          - containerPort: 7474
            name: neo4j_http
          - containerPort: 7687
            name: neo4j_bolt
          - containerPort: 7473
            name: neo4j_https
        env:
          - name: NEO4J_HOST
            value: "0.0.0.0"
          - name: NEO4J_HTTP_PORT
            value: 7474
          - name: NEO4J_BOLT_PORT
            value: 7687
          - name: NEO4J_HTTPS_PORT
            value: 7473
          - name: NEO4J_PASSWORD
            value: "neo4jkp"
      restartPolicy: Always
